name: in_service
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dotted_border: ^2.1.0
  easy_refresh: ^3.3.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  flutter_typeahead: ^4.3.7
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  geolocator: ^10.1.0
  get: ^4.6.6
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.5
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  loading_animation_widget: ^1.2.0+4
  nb_utils: ^6.1.0
  pin_code_fields: ^8.0.1
  retrofit: ^3.0.1+1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^4.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  image_path: "assets/icons/logo.png"